from Personnel import Personne,Employe,Eleve
import copy

emp1=Employe(1233,"soulaiman","karomi",31,"chef")
emp2=Employe(1232,"saad","sa",20,"Stagaire")
emp3=Employe(1231,"fahd","farid",22,"Securite")
elev1=Eleve(1234,"sal","walid",20,"1er anne",18)
elev2=Eleve(1235,"salo","adam",20,"2eme anne",19)
elev3=Eleve(1236,"salmi","mohamed",20,"3eme anne",13)
print(elev1.ToString())
print(elev1.Equals(elev2))
print(elev2.ToString())
print(elev2.Equals(elev3))
print(elev3.ToString())
print(elev3.Equals(elev1))
print(emp1.ToString())
print(emp1.Equals(emp2))
print(emp2.ToString())
print(emp2.Equals(emp3))
print(emp3.ToString())
print(emp3.Equals(emp1))
print(f"Le nombre Totale est: {Personne._count}")
print(f"Le nombre de eleves est: {Eleve._counttt}")
print(f"Le nombre d employer est: {Employe._countt}")